export interface RFIData {
  id: string
  rfiNumber: string
  status: 'Open' | 'Closed' | 'Draft'
  subject: string
  rfiManager: string
  assignee: string
  dueDate: string
  createdBy: string
  creationDate: string
  officialResponse: string
  costImpact: 'Yes' | 'No' | 'TBD' | 'N/A'
  costAmount?: string
  scheduleImpact: 'Yes' | 'No' | 'TBD' | 'N/A'
  scheduleDays?: number
  location: string
  costCode: string
  responsibleContractor: string
  isPrivate: boolean
  hasRelatedItems: boolean
  hasChangeHistory: boolean
}

export const MOCK_RFI_DATA: RFIData[] = [
  {
    id: '1',
    rfiNumber: 'RFI-234',
    status: 'Open',
    subject: 'Structural beam clarification - Load capacity for Level 5 transfer beams',
    rfiManager: 'Sarah Chen',
    assignee: 'Mike Torres',
    dueDate: '01/15/2026',
    createdBy: 'David Kim',
    creationDate: '01/02/2026',
    officialResponse: 'Pending structural engineer review',
    costImpact: 'TBD',
    scheduleImpact: 'No',
    location: 'Level 5, Grid E-F',
    costCode: '03-110',
    responsibleContractor: 'Atlas Steel',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '2',
    rfiNumber: 'RFI-235',
    status: 'Open',
    subject: 'HVAC duct routing conflict with electrical conduit in ceiling space',
    rfiManager: 'Jennifer Lee',
    assignee: 'Robert Martinez',
    dueDate: '01/18/2026',
    createdBy: 'Tom Wilson',
    creationDate: '01/05/2026',
    officialResponse: '',
    costImpact: 'Yes',
    costAmount: '$12,500',
    scheduleImpact: 'Yes',
    scheduleDays: 3,
    location: 'Level 3, Zone B',
    costCode: '23-310',
    responsibleContractor: 'Summit HVAC',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '3',
    rfiNumber: 'RFI-236',
    status: 'Closed',
    subject: 'Clarification on fire-rated wall assembly specification',
    rfiManager: 'Sarah Chen',
    assignee: 'Tom Wilson',
    dueDate: '01/10/2026',
    createdBy: 'Mike Torres',
    creationDate: '12/28/2025',
    officialResponse: 'Use UL-rated assembly per spec section 09-22-16',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'Level 2, Stairwell A',
    costCode: '09-220',
    responsibleContractor: 'BuildRight',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: true,
  },
  {
    id: '4',
    rfiNumber: 'RFI-237',
    status: 'Draft',
    subject: 'Window glazing specification - performance requirements unclear',
    rfiManager: 'Mike Torres',
    assignee: '',
    dueDate: '',
    createdBy: 'Jennifer Lee',
    creationDate: '01/12/2026',
    officialResponse: '',
    costImpact: 'TBD',
    scheduleImpact: 'TBD',
    location: 'East Facade',
    costCode: '08-810',
    responsibleContractor: 'Vista Glass',
    isPrivate: true,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '5',
    rfiNumber: 'RFI-238',
    status: 'Open',
    subject: 'Foundation waterproofing membrane installation method',
    rfiManager: 'Jennifer Lee',
    assignee: 'David Kim',
    dueDate: '01/20/2026',
    createdBy: 'Sarah Chen',
    creationDate: '01/08/2026',
    officialResponse: '',
    costImpact: 'No',
    scheduleImpact: 'TBD',
    location: 'Foundation Level',
    costCode: '07-120',
    responsibleContractor: 'WaterSeal Pro',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '6',
    rfiNumber: 'RFI-239',
    status: 'Open',
    subject: 'Parking garage lighting fixture mounting height discrepancy',
    rfiManager: 'Sarah Chen',
    assignee: 'Amanda Rodriguez',
    dueDate: '01/16/2026',
    createdBy: 'Robert Martinez',
    creationDate: '01/03/2026',
    officialResponse: '',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'Parking Level P1',
    costCode: '26-510',
    responsibleContractor: 'BrightWay Electric',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '7',
    rfiNumber: 'RFI-240',
    status: 'Closed',
    subject: 'Concrete mix design approval for exposed architectural finish',
    rfiManager: 'Mike Torres',
    assignee: 'Sarah Chen',
    dueDate: '01/12/2026',
    createdBy: 'Jennifer Lee',
    creationDate: '12/29/2025',
    officialResponse: 'Mix design SD-450 approved with architectural finish per mockup',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'Lobby, Feature Wall',
    costCode: '03-310',
    responsibleContractor: 'Premier Concrete',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: true,
  },
  {
    id: '8',
    rfiNumber: 'RFI-241',
    status: 'Open',
    subject: 'Elevator pit sump pump sizing and discharge routing',
    rfiManager: 'Jennifer Lee',
    assignee: 'Robert Martinez',
    dueDate: '01/22/2026',
    createdBy: 'Tom Wilson',
    creationDate: '01/10/2026',
    officialResponse: '',
    costImpact: 'TBD',
    scheduleImpact: 'No',
    location: 'Elevator Bank A',
    costCode: '21-410',
    responsibleContractor: 'Vertical Transport Inc',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '9',
    rfiNumber: 'RFI-242',
    status: 'Open',
    subject: 'Roof drain sizing and overflow scupper locations',
    rfiManager: 'Sarah Chen',
    assignee: 'Mike Torres',
    dueDate: '01/25/2026',
    createdBy: 'Amanda Rodriguez',
    creationDate: '01/11/2026',
    officialResponse: '',
    costImpact: 'No',
    scheduleImpact: 'TBD',
    location: 'Roof Level',
    costCode: '07-620',
    responsibleContractor: 'TopSeal Roofing',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '10',
    rfiNumber: 'RFI-243',
    status: 'Closed',
    subject: 'Exterior stone cladding anchor system specification',
    rfiManager: 'Mike Torres',
    assignee: 'Sarah Chen',
    dueDate: '01/08/2026',
    createdBy: 'Jennifer Lee',
    creationDate: '12/20/2025',
    officialResponse: 'Use stainless steel anchors per detail A5.21',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'South Facade',
    costCode: '04-420',
    responsibleContractor: 'Heritage Stone',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: true,
  },
  {
    id: '11',
    rfiNumber: 'RFI-244',
    status: 'Open',
    subject: 'Emergency generator fuel tank location and ventilation requirements',
    rfiManager: 'Jennifer Lee',
    assignee: 'David Kim',
    dueDate: '01/28/2026',
    createdBy: 'Robert Martinez',
    creationDate: '01/14/2026',
    officialResponse: '',
    costImpact: 'Yes',
    costAmount: '$8,200',
    scheduleImpact: 'Yes',
    scheduleDays: 5,
    location: 'Mechanical Room B',
    costCode: '26-320',
    responsibleContractor: 'PowerGen Systems',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '12',
    rfiNumber: 'RFI-245',
    status: 'Draft',
    subject: 'Interior partition wall sound rating requirements',
    rfiManager: 'Sarah Chen',
    assignee: '',
    dueDate: '',
    createdBy: 'Tom Wilson',
    creationDate: '01/15/2026',
    officialResponse: '',
    costImpact: 'TBD',
    scheduleImpact: 'TBD',
    location: 'Level 4, Conference Rooms',
    costCode: '09-210',
    responsibleContractor: 'InteriorPro',
    isPrivate: true,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '13',
    rfiNumber: 'RFI-246',
    status: 'Open',
    subject: 'Fire sprinkler head placement in coffered ceiling areas',
    rfiManager: 'Mike Torres',
    assignee: 'Amanda Rodriguez',
    dueDate: '01/30/2026',
    createdBy: 'David Kim',
    creationDate: '01/16/2026',
    officialResponse: '',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'Level 2, Main Lobby',
    costCode: '21-130',
    responsibleContractor: 'FireSafe Systems',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '14',
    rfiNumber: 'RFI-247',
    status: 'Closed',
    subject: 'Stair handrail termination detail at landings',
    rfiManager: 'Jennifer Lee',
    assignee: 'Mike Torres',
    dueDate: '01/05/2026',
    createdBy: 'Sarah Chen',
    creationDate: '12/18/2025',
    officialResponse: 'Return handrail to wall per ADA requirements',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'All Stairwells',
    costCode: '05-520',
    responsibleContractor: 'MetalWorks Inc',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: true,
  },
  {
    id: '15',
    rfiNumber: 'RFI-248',
    status: 'Open',
    subject: 'Loading dock door operation and safety interlock sequence',
    rfiManager: 'Sarah Chen',
    assignee: 'Robert Martinez',
    dueDate: '02/01/2026',
    createdBy: 'Jennifer Lee',
    creationDate: '01/17/2026',
    officialResponse: '',
    costImpact: 'TBD',
    scheduleImpact: 'No',
    location: 'Loading Dock',
    costCode: '08-360',
    responsibleContractor: 'DoorTech Solutions',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '16',
    rfiNumber: 'RFI-249',
    status: 'Open',
    subject: 'Curtain wall expansion joint locations and sealant specification',
    rfiManager: 'Mike Torres',
    assignee: 'Tom Wilson',
    dueDate: '02/03/2026',
    createdBy: 'Amanda Rodriguez',
    creationDate: '01/18/2026',
    officialResponse: '',
    costImpact: 'Yes',
    costAmount: '$15,800',
    scheduleImpact: 'Yes',
    scheduleDays: 4,
    location: 'North Facade',
    costCode: '08-440',
    responsibleContractor: 'GlassFront Systems',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '17',
    rfiNumber: 'RFI-250',
    status: 'Closed',
    subject: 'Plumbing fixture rough-in dimensions for accessible restrooms',
    rfiManager: 'Jennifer Lee',
    assignee: 'David Kim',
    dueDate: '01/02/2026',
    createdBy: 'Mike Torres',
    creationDate: '12/15/2025',
    officialResponse: 'Dimensions confirmed per ADA 2024 standards',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'All Floors, Restrooms',
    costCode: '22-410',
    responsibleContractor: 'PlumbRight',
    isPrivate: false,
    hasRelatedItems: false,
    hasChangeHistory: true,
  },
  {
    id: '18',
    rfiNumber: 'RFI-251',
    status: 'Open',
    subject: 'Telecommunication room cooling requirements and HVAC coordination',
    rfiManager: 'Sarah Chen',
    assignee: 'Robert Martinez',
    dueDate: '02/05/2026',
    createdBy: 'Tom Wilson',
    creationDate: '01/19/2026',
    officialResponse: '',
    costImpact: 'Yes',
    costAmount: '$22,000',
    scheduleImpact: 'TBD',
    location: 'Level 3, Telecom Room',
    costCode: '27-110',
    responsibleContractor: 'DataComm Contractors',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
  {
    id: '19',
    rfiNumber: 'RFI-252',
    status: 'Draft',
    subject: 'Landscape irrigation system backflow preventer location',
    rfiManager: 'Mike Torres',
    assignee: '',
    dueDate: '',
    createdBy: 'Jennifer Lee',
    creationDate: '01/20/2026',
    officialResponse: '',
    costImpact: 'TBD',
    scheduleImpact: 'TBD',
    location: 'Exterior, North Plaza',
    costCode: '32-840',
    responsibleContractor: 'GreenScape Design',
    isPrivate: true,
    hasRelatedItems: false,
    hasChangeHistory: false,
  },
  {
    id: '20',
    rfiNumber: 'RFI-253',
    status: 'Open',
    subject: 'Structural steel connection detail at cantilevered canopy',
    rfiManager: 'Jennifer Lee',
    assignee: 'Sarah Chen',
    dueDate: '02/08/2026',
    createdBy: 'David Kim',
    creationDate: '01/21/2026',
    officialResponse: '',
    costImpact: 'No',
    scheduleImpact: 'No',
    location: 'Main Entry Canopy',
    costCode: '05-120',
    responsibleContractor: 'Atlas Steel',
    isPrivate: false,
    hasRelatedItems: true,
    hasChangeHistory: false,
  },
]
