export interface OpenItem {
  id: string
  type:
    | 'RFI'
    | 'Submittal'
    | 'Inspection'
    | 'Change Order'
    | 'Daily Log'
    | 'Observation'
    | 'Meeting'
  description: string
  status: 'Open' | 'Pending Review' | 'In Progress'
  date: string
  dueDate: string
  assignee: string
  project?: string
  overdue?: boolean
}

export const MOCK_OPEN_ITEMS: OpenItem[] = [
  {
    id: '1',
    type: 'RFI',
    description: 'Electrical panel location conflicts with fire pump controller per Drawing E-201 Rev. 3',
    status: 'Open',
    date: '01/05/2025',
    dueDate: '01/20/2025',
    assignee: 'Sarah Chen',
    project: 'Skyline Tower',
    overdue: true,
  },
  {
    id: '2',
    type: 'Submittal',
    description: 'Structural steel shop drawings for Level 14-22 framing package',
    status: 'Pending Review',
    date: '01/06/2025',
    dueDate: '01/25/2025',
    assignee: 'Mike Rodriguez',
    project: 'Harbor Bridge Renovation',
  },
  {
    id: '3',
    type: 'Inspection',
    description: 'Concrete pour inspection required for foundation section B-7 through B-12',
    status: 'In Progress',
    date: '01/07/2025',
    dueDate: '01/15/2025',
    assignee: 'Emily Watson',
    project: 'Riverside Medical Center',
  },
  {
    id: '4',
    type: 'Change Order',
    description: 'PCO-042: Add waterproofing membrane to parking deck levels P1-P3',
    status: 'Pending Review',
    date: '01/08/2025',
    dueDate: '01/22/2025',
    assignee: 'David Kim',
    project: 'Skyline Tower',
  },
  {
    id: '5',
    type: 'RFI',
    description: 'Clarification on HVAC duct routing through shaft wall at grid line G-7',
    status: 'Open',
    date: '01/09/2025',
    dueDate: '01/18/2025',
    assignee: 'Sarah Chen',
    project: 'Harbor Bridge Renovation',
    overdue: true,
  },
  {
    id: '6',
    type: 'Observation',
    description: 'Rebar spacing non-compliance observed at column C-14, Level 3 slab pour',
    status: 'Open',
    date: '01/10/2025',
    dueDate: '01/14/2025',
    assignee: 'Mike Rodriguez',
    project: 'Skyline Tower',
    overdue: true,
  },
  {
    id: '7',
    type: 'Submittal',
    description: 'Mechanical equipment submittals for rooftop HVAC units RTU-1 through RTU-6',
    status: 'Pending Review',
    date: '01/10/2025',
    dueDate: '01/28/2025',
    assignee: 'Emily Watson',
    project: 'Riverside Medical Center',
  },
  {
    id: '8',
    type: 'Meeting',
    description: 'Weekly OAC coordination meeting — agenda and minutes for January 10 session',
    status: 'In Progress',
    date: '01/10/2025',
    dueDate: '01/17/2025',
    assignee: 'David Kim',
    project: 'Harbor Bridge Renovation',
  },
  {
    id: '9',
    type: 'Daily Log',
    description: 'Missing daily log entries for crew B — January 6-8 weather delay documentation',
    status: 'Open',
    date: '01/11/2025',
    dueDate: '01/13/2025',
    assignee: 'Sarah Chen',
    project: 'Skyline Tower',
    overdue: true,
  },
  {
    id: '10',
    type: 'Inspection',
    description: 'Pre-pour inspection for elevated slab at Level 8 — east and west wings',
    status: 'Open',
    date: '01/11/2025',
    dueDate: '01/21/2025',
    assignee: 'Mike Rodriguez',
    project: 'Riverside Medical Center',
  },
  {
    id: '11',
    type: 'Change Order',
    description: 'PCO-051: Scope change for underground utility relocation at main entry drive',
    status: 'Pending Review',
    date: '01/12/2025',
    dueDate: '01/26/2025',
    assignee: 'Emily Watson',
    project: 'Skyline Tower',
  },
  {
    id: '12',
    type: 'RFI',
    description: 'Window head flashing detail missing from Spec Section 07 27 00 at grid lines A-D',
    status: 'Open',
    date: '01/12/2025',
    dueDate: '01/19/2025',
    assignee: 'David Kim',
    project: 'Harbor Bridge Renovation',
  },
  {
    id: '13',
    type: 'Submittal',
    description: 'Exterior cladding system — aluminum composite panel mockup approval',
    status: 'In Progress',
    date: '01/13/2025',
    dueDate: '01/30/2025',
    assignee: 'Sarah Chen',
    project: 'Riverside Medical Center',
  },
  {
    id: '14',
    type: 'Observation',
    description: 'Concrete surface finish out of tolerance at parking structure Level 2 deck',
    status: 'Pending Review',
    date: '01/13/2025',
    dueDate: '01/20/2025',
    assignee: 'Mike Rodriguez',
    project: 'Skyline Tower',
  },
  {
    id: '15',
    type: 'Inspection',
    description: 'Anchor bolt inspection before column base plate grouting — grids 1-8 / A-D',
    status: 'Open',
    date: '01/14/2025',
    dueDate: '01/16/2025',
    assignee: 'Emily Watson',
    project: 'Harbor Bridge Renovation',
    overdue: true,
  },
  {
    id: '16',
    type: 'Meeting',
    description: 'Design coordination clash detection review with BIM team — Levels 10-15',
    status: 'In Progress',
    date: '01/14/2025',
    dueDate: '01/17/2025',
    assignee: 'David Kim',
    project: 'Riverside Medical Center',
  },
  {
    id: '17',
    type: 'RFI',
    description: 'Toilet room rough-in dimensions conflict with plumbing fixture schedule Rev. B',
    status: 'Open',
    date: '01/15/2025',
    dueDate: '01/22/2025',
    assignee: 'Sarah Chen',
    project: 'Skyline Tower',
  },
  {
    id: '18',
    type: 'Change Order',
    description: 'PCO-058: Emergency generator pad location revised per utility easement clearance',
    status: 'Open',
    date: '01/15/2025',
    dueDate: '01/24/2025',
    assignee: 'Mike Rodriguez',
    project: 'Harbor Bridge Renovation',
  },
  {
    id: '19',
    type: 'Daily Log',
    description: 'Safety incident report documentation required for near-miss event on Level 6',
    status: 'Open',
    date: '01/16/2025',
    dueDate: '01/17/2025',
    assignee: 'Emily Watson',
    project: 'Skyline Tower',
    overdue: true,
  },
  {
    id: '20',
    type: 'Submittal',
    description: 'Fire suppression system — sprinkler head layout drawings and cut sheets',
    status: 'Pending Review',
    date: '01/16/2025',
    dueDate: '02/01/2025',
    assignee: 'David Kim',
    project: 'Riverside Medical Center',
  },
]
