// Tool Registry - All icons use RiFill variants
import type { IconType } from "react-icons"
import {
  RiAlertFill,
  RiArchiveFill,
  RiAuctionFill,
  RiAwardFill,
  RiBankCardFill,
  RiBarChartBoxFill,
  RiBox3Fill,
  RiBriefcaseFill,
  RiCalculatorFill,
  RiCalendarFill,
  RiCalendarScheduleFill,
  RiCameraFill,
  RiChat3Fill,
  RiDashboardFill,
  RiDatabase2Fill,
  RiEditFill,
  RiEyeFill,
  RiFileCheckFill,
  RiFileEditFill,
  RiFileTextFill,
  RiFlowChart,
  RiFolderOpenFill,
  RiHandCoinFill,
  RiHeartFill,
  RiHomeFill,
  RiImageFill,
  RiLineChartFill,
  RiLinksFill,
  RiListCheck2,
  RiLockFill,
  RiMailFill,
  RiMoneyDollarCircleFill,
  RiPulseFill,
  RiQuestionFill,
  RiReceiptFill,
  RiRobotFill,
  RiSendPlaneFill,
  RiSettings4Fill,
  RiShieldFill,
  RiStackFill,
  RiSurveyFill,
  RiTeamFill,
  RiTicketFill,
  RiTimeFill,
  RiToolsFill,
  RiTruckFill,
  RiUploadCloud2Fill,
  RiUserFollowFill,
  RiVideoFill,
} from "react-icons/ri"

export interface ToolDefinition {
  id: string
  name: string
  category: string
  icon: IconType
  path: string
  context: "company" | "project"
  mobileCritical?: boolean
  badges?: ("beta" | "new" | "updated" | "merged" | "legacy" | "pilot")[]
  description?: string
  relatedTools?: string[]
}

export interface MenuSection {
  id: string
  label: string
  icon: IconType
  illustration?: string   // path relative to /public, e.g. "/illustrations/core-platform.png"
  description?: string
  badge?: string
  tools: string[]
}

// Company Tools
export const COMPANY_TOOLS: Record<string, ToolDefinition> = {
  "portfolio": {
    id: "portfolio",
    name: "Portfolio",
    category: "core",
    icon: RiBriefcaseFill,
    path: "/portfolio",
    context: "company",
  },
  "programs": {
    id: "programs",
    name: "Programs",
    category: "core",
    icon: RiStackFill,
    path: "/programs",
    context: "company",
  },
  "directory-company": {
    id: "directory-company",
    name: "Directory",
    category: "core",
    icon: RiTeamFill,
    path: "/directory",
    context: "company",
  },
  "360-reporting": {
    id: "360-reporting",
    name: "360 Reporting",
    category: "core",
    icon: RiBarChartBoxFill,
    path: "/reporting",
    context: "company",
  },
  "analytics": {
    id: "analytics",
    name: "Analytics",
    category: "core",
    icon: RiLineChartFill,
    path: "/analytics",
    context: "company",
  },
  "admin-company": {
    id: "admin-company",
    name: "Admin",
    category: "admin",
    icon: RiSettings4Fill,
    path: "/admin",
    context: "company",
  },
  "permissions": {
    id: "permissions",
    name: "Permissions",
    category: "admin",
    icon: RiLockFill,
    path: "/permissions",
    context: "company",
  },
  "app-management": {
    id: "app-management",
    name: "App Management",
    category: "admin",
    icon: RiArchiveFill,
    path: "/apps",
    context: "company",
  },
  "workflows-company": {
    id: "workflows-company",
    name: "Workflows",
    category: "admin",
    icon: RiFlowChart,
    path: "/workflows",
    context: "company",
  },
  "connection-manager": {
    id: "connection-manager",
    name: "Connection Manager",
    category: "admin",
    icon: RiLinksFill,
    path: "/connections",
    context: "company",
    badges: ["new"],
    description: "Now you can sync your information between all projects.",
  },
  "financials-dashboard": {
    id: "financials-dashboard",
    name: "Financials Dashboard",
    category: "financial",
    icon: RiMoneyDollarCircleFill,
    path: "/financials",
    context: "company",
  },
  "project-status-snapshots": {
    id: "project-status-snapshots",
    name: "Project Status Snapshots",
    category: "financial",
    icon: RiCameraFill,
    path: "/snapshots",
    context: "company",
  },
  "erp-integrations": {
    id: "erp-integrations",
    name: "ERP Integrations",
    category: "financial",
    icon: RiLinksFill,
    path: "/erp",
    context: "company",
  },
  "resource-planning-company": {
    id: "resource-planning-company",
    name: "Resource Planning",
    category: "resources",
    icon: RiUserFollowFill,
    path: "/resource-planning",
    context: "company",
  },
  "timesheets-company": {
    id: "timesheets-company",
    name: "Timesheets",
    category: "resources",
    icon: RiTimeFill,
    path: "/timesheets",
    context: "company",
  },
  "equipment-company": {
    id: "equipment-company",
    name: "Equipment",
    category: "resources",
    icon: RiTruckFill,
    path: "/equipment",
    context: "company",
    badges: ["legacy"],
  },
  "planroom": {
    id: "planroom",
    name: "Planroom",
    category: "preconstruction",
    icon: RiImageFill,
    path: "/planroom",
    context: "company",
  },
  "bid-board": {
    id: "bid-board",
    name: "Bid Board",
    category: "preconstruction",
    icon: RiAuctionFill,
    path: "/bid-board",
    context: "company",
  },
  "prequalifications": {
    id: "prequalifications",
    name: "Prequalifications",
    category: "preconstruction",
    icon: RiAwardFill,
    path: "/prequalifications",
    context: "company",
  },
  "prequalification-portal": {
    id: "prequalification-portal",
    name: "Prequalification Portal",
    category: "preconstruction",
    icon: RiFileCheckFill,
    path: "/prequalification-portal",
    context: "company",
  },
  "cost-catalog": {
    id: "cost-catalog",
    name: "Cost Catalog",
    category: "preconstruction",
    icon: RiCalculatorFill,
    path: "/cost-catalog",
    context: "company",
  },
  "executive-dashboard": {
    id: "executive-dashboard",
    name: "Executive Dashboard",
    category: "insights",
    icon: RiDashboardFill,
    path: "/executive",
    context: "company",
  },
  "project-management-dashboard": {
    id: "project-management-dashboard",
    name: "Project Management Dashboard",
    category: "insights",
    icon: RiBarChartBoxFill,
    path: "/project-management",
    context: "company",
  },
  "quality-safety-dashboard": {
    id: "quality-safety-dashboard",
    name: "Quality & Safety Dashboard",
    category: "insights",
    icon: RiShieldFill,
    path: "/quality-safety",
    context: "company",
  },
  "health-dashboard": {
    id: "health-dashboard",
    name: "Health Dashboard",
    category: "insights",
    icon: RiHeartFill,
    path: "/health",
    context: "company",
  },
  "data-extracts": {
    id: "data-extracts",
    name: "Data Extracts",
    category: "advanced",
    icon: RiDatabase2Fill,
    path: "/data-extracts",
    context: "company",
    badges: ["beta"],
  },
  "assets": {
    id: "assets",
    name: "Assets",
    category: "advanced",
    icon: RiArchiveFill,
    path: "/assets",
    context: "company",
    badges: ["beta"],
  },
  "link": {
    id: "link",
    name: "Link",
    category: "advanced",
    icon: RiLinksFill,
    path: "/link",
    context: "company",
    badges: ["pilot"],
  },
}

// Project Tools
export const PROJECT_TOOLS: Record<string, ToolDefinition> = {
  "rfis": {
    id: "rfis",
    name: "RFIs",
    category: "coordination",
    icon: RiQuestionFill,
    path: "/rfis",
    context: "project",
    mobileCritical: true,
    relatedTools: ["submittals", "change-events", "drawings"],
  },
  "submittals": {
    id: "submittals",
    name: "Submittals",
    category: "coordination",
    icon: RiUploadCloud2Fill,
    path: "/submittals",
    context: "project",
    relatedTools: ["rfis", "drawings", "specifications"],
  },
  "correspondence": {
    id: "correspondence",
    name: "Correspondence",
    category: "coordination",
    icon: RiMailFill,
    path: "/correspondence",
    context: "project",
  },
  "meetings": {
    id: "meetings",
    name: "Meetings",
    category: "coordination",
    icon: RiVideoFill,
    path: "/meetings",
    context: "project",
  },
  "transmittals": {
    id: "transmittals",
    name: "Transmittals",
    category: "coordination",
    icon: RiSendPlaneFill,
    path: "/transmittals",
    context: "project",
  },
  "emails": {
    id: "emails",
    name: "Emails",
    category: "coordination",
    icon: RiMailFill,
    path: "/emails",
    context: "project",
  },
  "coordination-issues": {
    id: "coordination-issues",
    name: "Coordination Issues",
    category: "coordination",
    icon: RiToolsFill,
    path: "/coordination-issues",
    context: "project",
  },
  "observations": {
    id: "observations",
    name: "Observations",
    category: "field",
    icon: RiEyeFill,
    path: "/observations",
    context: "project",
    mobileCritical: true,
    badges: ["merged"],
    description: "Quality & Safety Observations combined",
  },
  "inspections": {
    id: "inspections",
    name: "Inspections",
    category: "field",
    icon: RiSurveyFill,
    path: "/inspections",
    context: "project",
    mobileCritical: true,
    badges: ["merged"],
    description: "Quality & Safety Inspections combined",
  },
  "daily-log": {
    id: "daily-log",
    name: "Daily Log",
    category: "field",
    icon: RiCalendarFill,
    path: "/daily-log",
    context: "project",
  },
  "photos": {
    id: "photos",
    name: "Photos",
    category: "field",
    icon: RiCameraFill,
    path: "/photos",
    context: "project",
  },
  "punch-list": {
    id: "punch-list",
    name: "Punch List",
    category: "field",
    icon: RiListCheck2,
    path: "/punch-list",
    context: "project",
  },
  "incidents": {
    id: "incidents",
    name: "Incidents",
    category: "field",
    icon: RiAlertFill,
    path: "/incidents",
    context: "project",
  },
  "drawings": {
    id: "drawings",
    name: "Drawings",
    category: "documents",
    icon: RiImageFill,
    path: "/drawings",
    context: "project",
    mobileCritical: true,
    relatedTools: ["specifications", "models", "rfis"],
  },
  "documents": {
    id: "documents",
    name: "Documents",
    category: "documents",
    icon: RiFolderOpenFill,
    path: "/documents",
    context: "project",
  },
  "specifications": {
    id: "specifications",
    name: "Specifications",
    category: "documents",
    icon: RiFileTextFill,
    path: "/specifications",
    context: "project",
  },
  "models": {
    id: "models",
    name: "Models",
    category: "documents",
    icon: RiBox3Fill,
    path: "/bim-models",
    context: "project",
  },
  "assemble": {
    id: "assemble",
    name: "Assemble",
    category: "documents",
    icon: RiStackFill,
    path: "/assemble",
    context: "project",
    description: "BIM coordination and takeoffs",
  },
  "budget": {
    id: "budget",
    name: "Budget",
    category: "financial",
    icon: RiCalculatorFill,
    path: "/budget",
    context: "project",
    relatedTools: ["change-events", "change-orders", "commitments"],
  },
  "change-events": {
    id: "change-events",
    name: "Change Events",
    category: "financial",
    icon: RiEditFill,
    path: "/change-events",
    context: "project",
    relatedTools: ["rfis", "budget", "change-orders"],
  },
  "change-orders": {
    id: "change-orders",
    name: "Change Orders",
    category: "financial",
    icon: RiFileEditFill,
    path: "/change-orders",
    context: "project",
  },
  "commitments": {
    id: "commitments",
    name: "Commitments",
    category: "financial",
    icon: RiHandCoinFill,
    path: "/commitments",
    context: "project",
  },
  "prime-contracts": {
    id: "prime-contracts",
    name: "Prime Contracts",
    category: "financial",
    icon: RiFileTextFill,
    path: "/prime-contracts",
    context: "project",
  },
  "direct-costs": {
    id: "direct-costs",
    name: "Direct Costs",
    category: "financial",
    icon: RiReceiptFill,
    path: "/direct-costs",
    context: "project",
    badges: ["beta"],
  },
  "invoicing": {
    id: "invoicing",
    name: "Invoicing",
    category: "financial",
    icon: RiBankCardFill,
    path: "/invoicing",
    context: "project",
  },
  "schedule": {
    id: "schedule",
    name: "Schedule",
    category: "resources",
    icon: RiCalendarScheduleFill,
    path: "/schedule",
    context: "project",
    badges: ["updated"],
    description: "Enhanced scheduling with new features",
  },
  "timesheets": {
    id: "timesheets",
    name: "Timesheets",
    category: "resources",
    icon: RiTimeFill,
    path: "/timesheets",
    context: "project",
  },
  "crews": {
    id: "crews",
    name: "Crews",
    category: "resources",
    icon: RiTeamFill,
    path: "/crews",
    context: "project",
  },
  "equipment": {
    id: "equipment",
    name: "Equipment",
    category: "resources",
    icon: RiTruckFill,
    path: "/equipment",
    context: "project",
  },
  "tm-tickets": {
    id: "tm-tickets",
    name: "T&M Tickets",
    category: "resources",
    icon: RiTicketFill,
    path: "/tm-tickets",
    context: "project",
  },
  "resource-planning-project": {
    id: "resource-planning-project",
    name: "Resource Planning",
    category: "resources",
    icon: RiUserFollowFill,
    path: "/resource-planning",
    context: "project",
  },
  "bidding": {
    id: "bidding",
    name: "Bidding",
    category: "preconstruction",
    icon: RiAuctionFill,
    path: "/bidding",
    context: "project",
  },
  "forms": {
    id: "forms",
    name: "Forms",
    category: "platform",
    icon: RiSurveyFill,
    path: "/forms",
    context: "project",
  },
  "instructions": {
    id: "instructions",
    name: "Instructions",
    category: "platform",
    icon: RiFileTextFill,
    path: "/instructions",
    context: "project",
  },
  "admin-project": {
    id: "admin-project",
    name: "Admin",
    category: "platform",
    icon: RiSettings4Fill,
    path: "/admin",
    context: "project",
  },
  "agent-builder": {
    id: "agent-builder",
    name: "Agent Builder",
    category: "advanced",
    icon: RiRobotFill,
    path: "/agent-builder",
    context: "project",
    badges: ["beta"],
    description: "AI automation workflows",
  },
}

// Menu Sections
export const COMPANY_MENU_SECTIONS: MenuSection[] = [
  {
    id: "core-platform",
    label: "Core Platform",
    icon: RiStackFill,
    illustration: "/illustrations/core-platform.png",
    tools: ["portfolio", "programs", "directory-company", "360-reporting", "analytics"],
  },
  {
    id: "administration",
    label: "Administration",
    icon: RiShieldFill,
    illustration: "/illustrations/administration.png",
    tools: ["admin-company", "permissions", "app-management", "workflows-company", "connection-manager"],
  },
  {
    id: "financial-management",
    label: "Financial Management",
    icon: RiMoneyDollarCircleFill,
    illustration: "/illustrations/financial-management.png",
    tools: ["financials-dashboard", "project-status-snapshots", "erp-integrations"],
  },
  {
    id: "resource-management",
    label: "Resource Management",
    icon: RiTeamFill,
    illustration: "/illustrations/resource-management.png",
    tools: ["resource-planning-company", "timesheets-company", "equipment-company"],
  },
  {
    id: "preconstruction",
    label: "Pre Construction",
    icon: RiImageFill,
    illustration: "/illustrations/pre-construction.png",
    tools: ["planroom", "bid-board", "prequalifications", "prequalification-portal", "cost-catalog"],
  },
  {
    id: "insights-dashboards",
    label: "Insights & Dashboards",
    icon: RiDashboardFill,
    illustration: "/illustrations/insights-dashboards.png",
    tools: ["executive-dashboard", "project-management-dashboard", "quality-safety-dashboard", "health-dashboard"],
  },
  {
    id: "advanced-tools",
    label: "Advanced Tools",
    icon: RiPulseFill,
    illustration: "/illustrations/advanced-tools.png",
    badge: "Beta",
    tools: ["data-extracts", "assets", "link"],
  },
]

export const PROJECT_MENU_SECTIONS: MenuSection[] = [
  {
    id: "coordination",
    label: "Coordination",
    icon: RiChat3Fill,
    illustration: "/illustrations/project-coordination.png",
    description: "Communication & collaboration",
    tools: ["rfis", "submittals", "correspondence", "meetings", "transmittals", "emails", "coordination-issues"],
  },
  {
    id: "field-management",
    label: "Field Management",
    icon: RiSurveyFill,
    illustration: "/illustrations/project-field-management.png",
    description: "Daily field operations",
    tools: ["observations", "inspections", "daily-log", "photos", "punch-list", "incidents"],
  },
  {
    id: "documents-plans",
    label: "Documents & Plans",
    icon: RiFolderOpenFill,
    illustration: "/illustrations/project-reporting.png",
    description: "Project documentation",
    tools: ["drawings", "documents", "specifications", "models", "assemble"],
  },
  {
    id: "financial-management",
    label: "Financial Management",
    icon: RiMoneyDollarCircleFill,
    illustration: "/illustrations/project-financial-management.png",
    description: "Project financials",
    tools: ["budget", "change-events", "change-orders", "commitments", "prime-contracts", "direct-costs", "invoicing"],
  },
  {
    id: "resources-schedule",
    label: "Resources & Schedule",
    icon: RiCalendarFill,
    illustration: "/illustrations/project-resource-management.png",
    description: "Resource management",
    tools: ["schedule", "timesheets", "crews", "equipment", "tm-tickets", "resource-planning-project"],
  },
  {
    id: "preconstruction",
    label: "Preconstruction",
    icon: RiImageFill,
    illustration: "/illustrations/project-pre-construction.png",
    description: "Pre-construction phase",
    tools: ["bidding"],
  },
  {
    id: "platform-tools",
    label: "Platform Tools",
    icon: RiSettings4Fill,
    illustration: "/illustrations/project-core-platform.png",
    description: "Configuration & setup",
    tools: ["forms", "instructions", "admin-project"],
  },
  {
    id: "advanced-features",
    label: "Advanced Features",
    icon: RiPulseFill,
    illustration: "/illustrations/project-advanced-tools.png",
    description: "Beta & experimental",
    badge: "Beta",
    tools: ["agent-builder"],
  },
]

// Helper Functions
export function getToolById(id: string): ToolDefinition | undefined {
  return COMPANY_TOOLS[id] || PROJECT_TOOLS[id]
}

export function getToolsByIds(ids: string[]): ToolDefinition[] {
  return ids.map(id => getToolById(id)).filter((tool): tool is ToolDefinition => tool !== undefined)
}

export function getMobileCriticalTools(): ToolDefinition[] {
  return Object.values(PROJECT_TOOLS).filter(tool => tool.mobileCritical)
}

export function getToolsByCategory(category: string, context: "company" | "project"): ToolDefinition[] {
  const tools = context === "company" ? COMPANY_TOOLS : PROJECT_TOOLS
  return Object.values(tools).filter(tool => tool.category === category)
}
